sudo: false
language: c
compiler:
    - gcc
os:
    - linux
before_script:
     -  ./autogen.sh
script:
    - ./configure --prefix=$PWD/gpi2-install-dir --with-ethernet --with-fortran=false
    - make
    - make install
after_failure:
    - cat ./config.log
after_script:
    - cat ./config.log
