BIN = loop_barrier.bin loop_barrier_group.bin loop_barrier_group_timeout.bin allreduce.bin \
	barrier_timeout.bin

CFLAGS+=-I../

build: $(BIN)

%.bin: %.o ../test_utils.o  
	$(CC) $(CFLAGS) $(LIB_PATH) -o $(TOPROOT)/bin/$@ $^ $(LIBS)
clean:
	rm -rf *~ \#_* *.o *.bin
